language: python
script:
  - ./_travis/run.sh
before_install:
  - env
  - openssl version
after_success:
  - ./_travis/upload_coverage.sh
cache:
  directories:
  - ${HOME}/.cache
install:
  - ./_travis/install.sh
notifications:
  email: false
env:
  global:
    - GAE_SDK_PATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning
  matrix:
    - TOXENV=gae
# https://github.com/travis-ci/travis-ci/issues/4794
matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8-py3
    - python: 3.6
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
      dist: xenial
      sudo: required
    - python: 3.8-dev
      env: TOXENV=py38
      dist: xenial
      sudo: required
    - python: pypy2.7
      env: TOXENV=pypy
    - python: pypy3.5
      env: TOXENV=pypy3
    - language: generic
      os: osx
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py34
    - language: generic
      os: osx
      env: TOXENV=py35
    - language: generic
      os: osx
      env: TOXENV=py36
    - language: generic
      os: osx
      env: TOXENV=py37
    - language: generic
      os: osx
      env: TOXENV=py38
  allow_failures:
    - python: 3.6
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py27
    - python: 3.4
      env: TOXENV=py34
    - python: pypy2.7
      env: TOXENV=pypy
    - python: pypy3.5
      env: TOXENV=pypy3
    - language: generic
      os: osx
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py34
sudo: false
