language: python
sudo: false
stage: test
dist: xenial

before_install:
  - env
  - openssl version
  - python -c "import ssl; print(ssl.OPENSSL_VERSION)"

install:
  - ./_travis/install.sh

script:
  - ./_travis/run.sh

after_success:
  - ./_travis/upload_coverage.sh

cache:
  directories:
  - ${HOME}/.cache

notifications:
  email: false

env:
  global:
    - GAE_SDK_PATH=${HOME}/.cache/google_appengine
    - PYTHONWARNINGS=always::DeprecationWarning

    - PYPI_USERNAME=urllib3
    # PYPI_PASSWORD is set in Travis control panel.

  matrix:
    # - TOXENV=flake8-py3
    # - TOXENV=gae
    - TOXENV=docs

matrix:
  include:
    - python: 3.6
      env: TOXENV=flake8-py3
    - python: 3.6
      env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=py27-nobrotli
    - python: 2.7
      env: TOXENV=py27-google-brotli
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.7
      env: TOXENV=py37-nobrotli
    - python: 3.7
      env: TOXENV=py37-google-brotli
    - python: 3.8-dev
      env: TOXENV=py38
    - python: pypy2.7-7.1.1
      env: TOXENV=pypy
    - python: pypy3.6-7.1.1
      env: TOXENV=pypy3
    - language: generic
      os: osx
      env: TOXENV=py27
    - language: generic
      os: osx
      env: TOXENV=py34
    - language: generic
      os: osx
      env: TOXENV=py35
    - language: generic
      os: osx
      env: TOXENV=py36
    - language: generic
      os: osx
      env: TOXENV=py37

    # - python: 2.7
    #   env: DOWNSTREAM=requests
    #   stage: integration

    # - python: 3.7
    #   env: DOWNSTREAM=requests
    #   stage: integration

    # - python: 2.7
    #   env: DOWNSTREAM=botocore
    #   stage: integration

    # - python: 3.7
    #   env: DOWNSTREAM=botocore
    #   stage: integration

    - python: 3.7
      stage: deploy
      script:
        - ./_travis/deploy.sh

  allow_failures:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.4
      env: TOXENV=py34
    - language: generic
      os: osx
      env: TOXENV=py34
    # MacPython 3.5 only supports TLS 1.1 by default, which fails whenever
    # easy_install fetchs packages, which is required by Twisted. Giving up on
    # testing MacPython 3.5 on Travis for this reason.
    # https://github.com/tox-dev/tox/issues/809#issuecomment-443436586
    - language: generic
      os: osx
      env: TOXENV=py35

stages:
  - name: test
    if: tag IS blank

  # Run integration tests for release candidates
  - name: integration
    if: type = pull_request AND head_branch =~ ^release-[\d.]+$ AND tag IS blank

  # Deploy on any tags
  - name: deploy
    if: branch = master AND tag IS present
